# Generated by Django 4.1.5 on 2023-02-02 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0002_alter_cities_interests_alter_cities_travel_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reviews', models.IntegerField()),
                ('open_close_time', models.JSONField()),
                ('spend_time', models.IntegerField()),
                ('matched', models.IntegerField()),
                ('travel_with', models.JSONField()),
                ('budget', models.CharField(max_length=255)),
                ('interest', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='places',
            field=models.ManyToManyField(to='cities.places'),
        ),
    ]
