# Generated by Django 4.1.5 on 2023-02-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_places_cities_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='places',
        ),
        migrations.AddField(
            model_name='places',
            name='city_name',
            field=models.CharField(default='Delhi', max_length=255),
        ),
    ]
