# Generated by Django 4.1.5 on 2023-02-04 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0004_remove_cities_places_places_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='free_times',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='travel_days',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='travel_with',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='user',
        ),
        migrations.RemoveField(
            model_name='places',
            name='user',
        ),
        migrations.AlterField(
            model_name='places',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.cities'),
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('travel_days', models.IntegerField()),
                ('free_times', models.CharField(max_length=255)),
                ('budget', models.CharField(max_length=255)),
                ('travel_with', models.JSONField()),
                ('interests', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='user_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cities.userform'),
        ),
    ]
