# Generated by Django 4.1.5 on 2023-02-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_remove_cities_user_form_userform_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='full_filter_query',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='partial_filter_query',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
