# Generated by Django 4.1.5 on 2023-02-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_userform_full_filter_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='city/'),
        ),
    ]
